data_for_ccna = {
    "2. What is the default subnet mask for a Class C IP address?": ["a) 0.0.0.0", "b) 255.255.0.0", "c) 255.0.0.0", "d) 255.255.255.0", {"Answer": "c"}],
    "3. Which protocol is used for secure file transfer over a network?": ["a) FTP", "b) TFTP", "c) SSH", "d) Telnet", {"Answer": "c"}],
    "4. What is the maximum number of hosts that can be addressed in a subnet with a /26 subnet mask?": ["a) 126", "b) 62", "c) 254", "d) 510", {"Answer": "b"}],
    "5. Which routing protocol uses the Bellman-Ford algorithm?": ["a) OSPF", "b) EIGRP", "c) RIP", "d) BGP", {"Answer": "c"}],
    "6. What is the default administrative distance of OSPF?": ["a) 90", "b) 100", "c) 110", "d) 120", {"Answer": "c"}],
    "7. Which device operates at Layer 2 of the OSI model?": ["a) Hub", "b) Switch", "c) Router", "d) Firewall", {"Answer": "b"}],
    "9. What is the maximum transmission speed of a standard Ethernet network?": ["a) 10 Mbps", "b) 100 Mbps", "c) 1 Gbps", "d) 10 Gbps", {"Answer": "b"}],
    "10. What is the purpose of a VLAN (Virtual Local Area Network)?": ["a) To segment a physical network into multiple logical networks", "b) To connect multiple geographically dispersed networks", "c) To provide wireless connectivity to network devices", "d) To establish a secure VPN connection", {"Answer": "a"}],
    "11. Which protocol is used to dynamically assign IP addresses to network devices?": ["a) ARP", "b) DNS", "c) DHCP", "d) ICMP", {"Answer": "c"}],
    "12. Which command is used to display the routing table on a Cisco router?": ["a) show interface", "b) show ip route", "c) show running-config", "d) show version", {"Answer": "b"}],
    "13. Which layer of the OSI model is responsible for framing and error detection?": ["a) Data Link Layer", "b) Network Layer", "c) Transport Layer", "d) Physical Layer", {"Answer": "a"}],
    "15. Which routing protocol uses a link-state database?": ["a) BGP", "b) EIGRP", "c) RIP", "d) OSPF", {"Answer": "d"}],
    "16. What is the default gateway for a network device?": ["a) The device's own IP address", "b) The IP address of the DNS server", "c) The IP address of the DHCP server", "d) The IP address of the router", {"Answer": "d"}],
    "17. Which command is used to test network connectivity between two devices?": ["a) traceroute", "b) ping", "c) netstat", "d) ipconfig", {"Answer": "b"}],
    "18. Which layer of the OSI model is responsible for flow control and error recovery?": ["a) Data Link Layer", "b) Network Layer", "c) Transport Layer", "d) Physical Layer", {"Answer": "c"}],
    "19. What is the maximum length of a cable segment in a 1000Base-T Ethernet network?": ["a) 2000 meters", "b) 500 meters", "c) 1000 meters", "d) 100 meters", {"Answer": "d"}],
    "20. Which command is used to display the MAC address of a network device?": ["a) ipconfig", "b) ifconfig", "c) arp", "d) ping", {"Answer": "c"}],
    "21. What is the purpose of a subnet mask?": ["a) To identify the network portion of an IP address", "b) To identify the host portion of an IP address", "c) To identify the default gateway for a network", "d) To identify the DNS server for a network", {"Answer": "a"}],
    "22. Which routing protocol uses a hybrid approach combining distance-vector and link-state algorithms?": ["a) OSPF", "b) EIGRP", "c) RIP", "d) BGP", {"Answer": "b"}],
    "23. Which command is used to display the MAC address table on a Cisco switch?": ["a) show mac address-table", "b) show ip interface brief", "c) show running-config", "d) show version", {"Answer": "a"}],
    "24. What is the purpose of NAT (Network Address Translation)?": ["a) To allow multiple devices to share a single public IP address", "b) To encrypt network traffic for security purposes", "c) To provide wireless connectivity to network devices", "d) To establish a secure VPN connection", {"Answer": "a"}],
    "25. Which protocol is used for secure web browsing?": ["a) HTTP", "b) FTP", "c) SSH", "d) HTTPS", {"Answer": "d"}],
    "26. Which command is used to display the ARP cache on a network device?": ["a) show arp", "b) show mac address-table", "c) show running-config", "d) show version", {"Answer": "a"}],
    "27. Which layer of the OSI model is responsible for routing and switching?": ["a) Data Link Layer", "b) Network Layer", "c) Transport Layer", "d) Physical Layer", {"Answer": "b"}],
    "28. Which command is used to display the interface configuration on a Cisco router?": ["a) show mac address-table", "b) show running-config", "c) show version", "d) show ip interface brief", {"Answer": "d"}],
    "29. What is the purpose of a default route?": ["a) To forward traffic to the next-hop router for which there is no specific route in the routing table", "b) To provide wireless connectivity to network devices", "c) To establish a secure VPN connection", "d) To encrypt network traffic for security purposes", {"Answer": "a"}],
    "30. Which protocol is used for email communication?": ["a) FTP", "b) SMTP", "c) SSH", "d) Telnet", {"Answer": "b"}],
    "31. Which command is used to display the version of the Cisco IOS running on a router?": ["a) show ip interface brief", "b) show running-config", "c) show version", "d) show mac address-table", {"Answer": "c"}],
    "34. Which routing protocol uses a hierarchical network design?": ["a) OSPF", "b) EIGRP", "c) RIP", "d) BGP", {"Answer": "d"}],
    "35. What is the purpose of a firewall?": ["a) To block unauthorized access to a network", "b) To provide wireless connectivity to network devices", "c) To establish a secure VPN connection", "d) To encrypt network traffic for security purposes", {"Answer": "a"}],
    "36. Which command is used to display the DNS configuration on a Windows computer?": ["a) ifconfig", "b) ipconfig", "c) nslookup", "d) netstat", {"Answer": "b"}],
    "37. Which layer of the OSI model is responsible for physical addressing?": ["a) Data Link Layer", "b) Network Layer", "c) Transport Layer", "d) Physical Layer", {"Answer": "a"}],
    "38. Which command is used to display the routing table on a Linux computer?": ["a) netstat", "b) ifconfig", "c) route", "d) ping", {"Answer": "c"}],
    "39. What is the purpose of a VPN (Virtual Private Network)?": ["a) To provide secure remote access to a network", "b) To provide wireless connectivity to network devices", "c) To encrypt network traffic for security purposes", "d) To establish a secure connection between two networks", {"Answer": "a"}],
    "40. Which protocol is used for DNS (Domain Name System) resolution?": ["a) FTP", "b) SMTP", "c) SSH", "d) UDP", {"Answer": "d"}],
    "41. Which command is used to display the routing table on a Windows computer?": ["a) nslookup", "b) ipconfig", "c) route print", "d) netstat", {"Answer": "c"}],
    "42. What is the purpose of a DMZ (Demilitarized Zone)?": ["a) To establish a secure VPN connection", "b) To provide wireless connectivity to network devices", "c) To provide a secure area for publicly accessible services", "d) To encrypt network traffic for security purposes", {"Answer": "c"}],
    "43. Which layer of the OSI model is responsible for error detection and correction?": ["a) Data Link Layer", "b) Network Layer", "c) Transport Layer", "d) Physical Layer", {"Answer": "d"}],
    "45. Which routing protocol uses a hierarchical network design with areas?": ["a) EIGRP", "b) OSPF", "c) RIP", "d) BGP", {"Answer": "b"}],
    "46. What is the purpose of a DHCP (Dynamic Host Configuration Protocol) server?": ["a) To establish a secure VPN connection", "b) To provide wireless connectivity to network devices", "c) To dynamically assign IP addresses to network devices", "d) To encrypt network traffic for security purposes", {"Answer": "c"}],
    "47. Which command is used to display the MAC address of a network device on a Windows computer?": ["a) ifconfig", "b)  ipconfig /all", "c) arp -a", "d) netstat", {"Answer": "b"}],
    "48. What is the purpose of a WAP (Wireless Access Point)?": ["a) To provide wireless connectivity to network devices", "b) To establish a secure VPN connection", "c) To encrypt network traffic for security purposes", "d) To block unauthorized access to a network", {"Answer": "a"}],
    "49. Which layer of the OSI model is responsible for logical addressing?": ["a) Data Link Layer", "b) Network Layer", "c) Transport Layer", "d) Physical Layer", {"Answer": "b"}],
    "51. What is the purpose of a static route?": ["a) To manually configure a specific route in the routing table", "b) To provide wireless connectivity to network devices", "c) To establish a secure VPN connection", "d) To encrypt network traffic for security purposes", {"Answer": "a"}],
    "52. Which protocol is used for remote access to a network device?": ["a) FTP", "b) TFTP", "c) SSH", "d) Telnet", {"Answer": "c"}],
    "53. What is the purpose of ARP (Address Resolution Protocol)?": ["a) To resolve IP addresses to MAC addresses", "b) To resolve domain names to IP addresses", "c) To establish a secure connection between two networks", "d) To encrypt network traffic for security purposes", {"Answer": "a"}],
    "54. Which layer of the OSI model is responsible for reliable data delivery?": ["a) Data Link Layer", "b) Network Layer", "c) Transport Layer", "d) Physical Layer", {"Answer": "c"}],
    "56. What is the purpose of a MAC address?": ["a) To identify a device on a network", "b) To identify the network portion of an IP address", "c) To identify the host portion of an IP address", "d) To identify the default gateway for a network", {"Answer": "a"}],
    "58. What is the purpose of a router?": ["a) To forward network traffic between different networks", "b) To provide wireless connectivity to network devices", "c) To establish a secure VPN connection", "d) To encrypt network traffic for security purposes", {"Answer": "a"}],
    "59. Which protocol is used to securely transfer files over a network?": ["a) FTP", "b) TFTP", "c) SSH", "d) Telnet", {"Answer": "c"}],
    "60. Which command is used to display the IP address configuration of a Cisco router?": ["a) show ip interface brief", "b) show running-config", "c) show version", "d) show mac address-table", {"Answer": "a"}],
    "64. What is the purpose of a gateway?": ["a) To provide access to another network", "b) To establish a secure VPN connection", "c) To encrypt network traffic for security purposes", "d) To block unauthorized access to a network", {"Answer": "a"}],
    "85. Which command is used to display the network interfaces on a Cisco router?": ["a) show ip interface brief", "b) show running-config", "c) show version", "d) show mac address-table", {"Answer": "a"}],
    "94. What is the purpose of a loopback interface?": ["a) To provide a stable IP address for internal network services", "b) To provide wireless connectivity to network devices", "c) To establish a secure VPN connection", "d) To test the functionality of a network interface card", {"Answer": "a"}],
    "99. What is the purpose of a DNS server?": ["a) To resolve domain names to IP addresses", "b) To provide wireless connectivity to network devices", "c) To establish a secure VPN connection", "d) To encrypt network traffic for security purposes", {"Answer": "a"}],
    "2. Which layer of the OSI model is responsible for reliable end-to-end delivery of data?": ["a) Physical Layer", "b) Network Layer", "c) Transport Layer", "d) Application Layer", {"Answer": "c"}],
    "4. Which layer of the OSI model is responsible for establishing and terminating connections between applications?": ["a) Physical Layer", "b) Network Layer", "c) Transport Layer", "d) Application Layer", {"Answer": "d"}],
    "7. What is the purpose of encapsulation in the OSI model?": ["a) Adding headers and trailers for transmission", "b) Establishing physical connections", "c) Error detection and correction", "d) Logical addressing and routing", {"Answer": "a"}],
    "8. Which layer of the OSI model is responsible for converting data into a format suitable for transmission over the network?": ["a) Physical Layer", "b) Network Layer", "c) Data Link Layer", "d) Presentation Layer", {"Answer": "d"}],
    "9. What is the primary function of the Transport Layer in the OSI model?": ["a) Logical addressing and routing", "b) Establishing physical connections", "c) Reliable end-to-end delivery of data", "d) Bit-level transmission", {"Answer": "c"}],
    "10. Which layer of the OSI model provides encryption and decryption of data?": ["a) Network Layer", "b) Data Link Layer", "c) Presentation Layer", "d) Session Layer", {"Answer": "c"}],
    "11. What is the purpose of the Session Layer in the OSI model?": ["a) Establishing physical connections", "b) Error detection and correction", "c) Managing communication sessions", "d) Bit-level transmission", {"Answer": "c"}],
    "13. What is the primary function of the Presentation Layer in the OSI model?": ["a) Logical addressing and routing", "b) Establishing physical connections", "c) Data encryption and decryption", "d) Bit-level transmission", {"Answer": "c"}],
    "14. Which layer of the OSI model is responsible for managing communication between devices on the same network?": ["a) Network Layer", "b) Data Link Layer", "c) Session Layer", "d) Presentation Layer", {"Answer": "b"}],
    "15. What is the role of the Network Layer in the OSI model?": ["a) Bit-level transmission", "b) Logical addressing and routing", "c) Error detection and correction", "d) Data encapsulation", {"Answer": "b"}],
    "16. Which layer of the OSI model is responsible for determining the best path for data to travel across multiple networks?": ["a) Data Link Layer", "b) Network Layer", "c) Transport Layer", "d) Physical Layer", {"Answer": "b"}],
    "17. What is the purpose of the Data Link Layer in the OSI model?": ["a) Frame synchronization", "b) Logical addressing and routing", "c) Error detection and correction", "d) Data encapsulation", {"Answer": "a"}],
    "18. Which layer of the OSI model provides services to the user, such as file transfer and email?": ["a) Physical Layer", "b) Network Layer", "c) Transport Layer", "d) Application Layer", {"Answer": "d"}],
    "19. What is the role of the Physical Layer in the OSI model?": ["a) Bit-level transmission", "b) Logical addressing and routing", "c) Error detection and correction", "d) Data encapsulation", {"Answer": "a"}],

}



