data_for_mcsa = {
    "1. Which layer of the OSI model is responsible for logical addressing and routing?": ["a) Data Link Layer", "b) Network Layer", "c) Transport Layer", "d) Physical Layer", {"Answer": "b"}],
    "2. What is the maximum number of logical processors supported by Windows Server 2019 Standard Edition?": ["a) 2", "b) 4", "c) 8", "d) 16", {"Answer": "c"}],
    "3. Which PowerShell cmdlet is used to create a new user account in Active Directory?": ["a) Set-ADUser", "b) New-ADUser", "c) Add-ADUser", "d) Create-ADUser", {"Answer": "b"}],
    "4. Which RAID level provides fault tolerance by mirroring data across multiple disks?": ["a) RAID 0", "b) RAID 1", "c) RAID 5", "d) RAID 10", {"Answer": "b"}],
    "5. Which Windows Server feature is used to deploy and manage virtual machines?": ["a) Remote Desktop Services (RDS)", "b) Hyper-V", "c) Windows Deployment Services (WDS)", "d) Windows Server Update Services (WSUS)", {"Answer": "b"}],
    "6. Which of the following is a Microsoft cloud-based service for identity and access management?": ["a) Azure Active Directory (Azure AD)", "b) Microsoft Intune", "c) Microsoft Azure Rights Management (Azure RMS)", "d) Azure Backup", {"Answer": "a"}],
    "7. Which Windows Server role is used for centralized network policy management and enforcement?": ["a) Remote Desktop Services (RDS)", "b) Network Policy and Access Services (NPAS)", "c) Active Directory Certificate Services (AD CS)", "d) Windows Server Update Services (WSUS)", {"Answer": "b"}],
    "8. Which PowerShell cmdlet is used to restart a Windows Server?": ["a) Restart-Computer", "b) Stop-Computer", "c) Shutdown-Computer", "d) Reboot-Computer", {"Answer": "a"}],
    "9. Which feature of Windows Server provides automatic IP address assignment to network devices?": ["a) DNS Server", "b) DHCP Server", "c) Network Load Balancing (NLB)", "d) File Server Resource Manager (FSRM)", {"Answer": "b"}],
    "10. Which Windows Server role is used for remote administration and management of servers?": ["a) Active Directory Lightweight Directory Services (AD LDS)", "b)  Remote Desktop Services (RDS)", "c) Internet Information Services (IIS)", "d) Windows Server Update Services (WSUS)", {"Answer": "b"}],
    "11. Which PowerShell cmdlet is used to create a new virtual machine in Hyper-V?": ["a) New-VM", "b) Set-VM", "c) Add-VM", "d) Create-VM", {"Answer": "a"}],
    "12. Which RAID level provides fault tolerance by striping data across multiple disks with parity information?": ["a) RAID 0", "b) RAID 1", "c) RAID 5", "d) RAID 10", {"Answer": "c"}],
    "13. Which Windows Server feature is used for centralized event log management and monitoring?": ["a) Event Viewer", "b) Performance Monitor", "c) Windows Firewall with Advanced Security", "d) Windows Admin Center", {"Answer": "d"}],
    "14. Which of the following is a Microsoft cloud-based service for data backup and recovery?": ["a) Azure Active Directory (Azure AD)", "b) Microsoft Intune", "c) Microsoft Azure Rights Management (Azure RMS)", "d) Azure Backup", {"Answer": "d"}],
    "15. Which Windows Server role is used for web server hosting and application deployment?": ["a) Active Directory Federation Services (AD FS)", "b) Remote Desktop Services (RDS)", "c) Internet Information Services (IIS)", "d) Windows Server Update Services (WSUS)", {"Answer": "c"}],
    "16. Which PowerShell cmdlet is used to create a new DNS zone in Windows Server?": ["a) Set-DnsServerZone", "b) New-DnsServerZone", "c) Add-DnsServerZone", "d) Create-DnsServerZone", {"Answer": "b"}],
    "17. Which RAID level provides fault tolerance by striping data across multiple disks without parity information?": ["a) RAID 0", "b) RAID 1", "c) RAID 5", "d) RAID 10", {"Answer": "a"}],
    "18. Which Windows Server feature is used for centralized software update management?": ["a) Hyper-V", "b) Remote Desktop Services (RDS)", "c) Windows Deployment Services (WDS)", "d) Windows Server Update Services (WSUS)", {"Answer": "d"}],
    "19. Which of the following is a Microsoft cloud-based service for mobile device management?": ["a) Azure Active Directory (Azure AD)", "b) Microsoft Intune", "c) Microsoft Azure Rights Management (Azure RMS)", "d) Azure Backup", {"Answer": "b"}],
    "20. Which Windows Server role is used for certificate management and public key infrastructure?": ["a) Remote Desktop Services (RDS)", "b) Active Directory Certificate Services (AD CS)", "c) Network Policy and Access Services (NPAS)", "d) Windows Server Update Services (WSUS)", {"Answer": "b"}],
    "21. Which PowerShell cmdlet is used to create a new file share in Windows Server?": ["a) New-SmbShare", "b) Set-SmbShare", "c) Add-SmbShare", "d) Create-SmbShare", {"Answer": "a"}],
    "22. Which RAID level provides fault tolerance by striping and mirroring data across multiple disks?": ["a) RAID 0", "b) RAID 1", "c) RAID 5", "d) RAID 10", {"Answer": "d"}],
    "23. Which Windows Server feature is used for centralized user profile management?": ["a) Hyper-V", "b) Remote Desktop Services (RDS)", "c) Windows Deployment Services (WDS)", "d) User State Virtualization (USV)", {"Answer": "d"}],
    "24. Which of the following is a Microsoft cloud-based service for information protection?": ["a) Azure Active Directory (Azure AD)", "b) Microsoft Intune", "c) Microsoft Azure Rights Management (Azure RMS)", "d) Azure Backup", {"Answer": "c"}],
    "25. Which Windows Server role is used for network load balancing and high availability?": ["a) Network Policy and Access Services (NPAS)", "b) Remote Desktop Services (RDS)", "c) Internet Information Services (IIS)", "d) Network Load Balancing (NLB)", {"Answer": "d"}],
    "26. Which PowerShell cmdlet is used to create a new firewall rule in Windows Server?": ["a) Add-NetFirewallRule", "b) Set-NetFirewallRule", "c) New-NetFirewallRule", "d) Create-NetFirewallRule", {"Answer": "c"}],
    "28. Which Windows Server feature is used for centralized printer management?": ["a) Print Management", "b) Performance Monitor", "c) Windows Firewall with Advanced Security", "d) Windows Admin Center", {"Answer": "a"}],
    "29. Which of the following is a Microsoft cloud-based service for virtual machine backup and disaster recovery?": ["a) Azure Active Directory (Azure AD)", "b) Microsoft Intune", "c) Microsoft Azure Rights Management (Azure RMS)", "d) Azure Site Recovery", {"Answer": "d"}],
    "30. Which Windows Server role is used for remote access and VPN connectivity?": ["a) Remote Desktop Services (RDS)", "b) Active Directory Federation Services (AD FS)", "c) Remote Access", "d) Windows Server Update Services (WSUS)", {"Answer": "c"}],
    "31. Which PowerShell cmdlet is used to create a new DHCP scope in Windows Server?": ["a) Add-DhcpServerv4Scope", "b) Set-DhcpServerv4Scope", "c) New-DhcpServerv4Scope", "d) Create-DhcpServerv4Scope", {"Answer": "c"}],
    "32. Which RAID level provides fault tolerance by striping data across multiple disks with distributed parity information?": ["a) RAID 0", "b) RAID 1", "c) RAID 5", "d) RAID 6", {"Answer": "c"}],
    "33. Which Windows Server feature is used for centralized remote management of servers and clusters?": ["a) Hyper-V", "b) Remote Desktop Services (RDS)", "c) Windows Admin Center", "d) Windows Server Update Services (WSUS)", {"Answer": "c"}],
    "34. Which of the following is a Microsoft cloud-based service for virtual machine hosting and management?": ["a) Azure Active Directory (Azure AD)", "b) Microsoft Intune", "c) Microsoft Azure Rights Management (Azure RMS)", "d) Azure Virtual Machines", {"Answer": "d"}],
    "35. Which Windows Server role is used for network policy management and enforcement?": ["a) Windows Server Update Services (WSUS)", "b) Remote Desktop Services (RDS)", "c) Active Directory Certificate Services (AD CS)", "d) Network Policy and Access Services (NPAS)", {"Answer": "d"}],
    "36. Which PowerShell cmdlet is used to create a new group policy object (GPO) in Windows Server?": ["a) New-GPO", "b) Set-GPO", "c) Add-GPO", "d) Create-GPO", {"Answer": "a"}],
    "37. Which RAID level provides fault tolerance by striping data across multiple disks with mirrored sets?": ["a) RAID 0", "b) RAID 1", "c) RAID 5", "d) RAID 10", {"Answer": "d"}],
    "38. Which Windows Server feature is used for centralized backup and recovery of files and folders?": ["a) Hyper-V", "b) Remote Desktop Services (RDS)", "c) Windows Server Backup", "d) Windows Server Update Services (WSUS)", {"Answer": "c"}]
}


data = {
    "2. What is the purpose of DHCP in a network?": ["a) Assigning IP addresses dynamically", "b) Resolving domain names to IP addresses", "c) Encrypting network traffic", "d) Managing network security", {"Answer": "a"}],
    "3. Which protocol is commonly used to transfer files over a network?": ["a) HTTP", "b) FTP", "c) SMTP", "d) SNMP", {"Answer": "b"}],
    "4. What is the default subnet mask for a Class C IP address?": ["a) 255.255.0.0", "b) 255.0.0.0", "c) 255.255.255.0", "d) 255.255.255.255", {"Answer": "c"}],
    "5. What is the purpose of a firewall in network security?": ["a) Filtering network traffic", "b) Assigning IP addresses", "c) Encrypting data transmission", "d) Managing network resources", {"Answer": "a"}],
    "6. What is the maximum transmission speed of a standard Ethernet connection?": ["a) 1 Gbps", "b) 100 Mbps", "c) 10 Mbps", "d) 1 Mbps", {"Answer": "b"}],
    "7. Which protocol is used to translate domain names to IP addresses?": ["a) DNS", "b) DHCP", "c) FTP", "d) HTTP", {"Answer": "a"}],
    "8. What is the purpose of RAID in data storage?": ["a) Redundancy and data protection", "b) Increasing data transfer speed", "c) Managing network traffic", "d) Securing network communication", {"Answer": "a"}],
    "9. What is the default port number for HTTP traffic?": ["a) 80", "b) 443", "c) 22", "d) 21", {"Answer": "a"}],
    "10. What is the purpose of NAT in network routing?": ["a) Translating private IP addresses to public IP addresses", "b) Securing network communication", "c) Load balancing network traffic", "d) Assigning IP addresses dynamically", {"Answer": "a"}],
    "11. Which command is used to check the connectivity between two network devices?": ["a) ping", "b) ssh", "c) telnet", "d) traceroute", {"Answer": "a"}],
    "12. What is the maximum number of hosts that can be assigned in a Class B network?": ["a) 254", "b) 65,534", "c) 16,777,214", "d) 4,294,966,584", {"Answer": "b"}],
    "13. Which cryptographic algorithm is commonly used for secure data transmission over the internet?": ["a) AES", "b) DES", "c) RSA", "d) MD5", {"Answer": "a"}],
    "14. What is the purpose of VLANs in network configuration?": ["a) Segmentation and isolation of network traffic", "b) Increasing network speed", "c) Assigning IP addresses", "d) Managing network security", {"Answer": "a"}],
    "15. What is the default gateway in a network configuration?": ["a) The IP address of the router", "b) The IP address of the DNS server", "c) The IP address of the DHCP server", "d) The IP address of the firewall", {"Answer": "a"}],
    "16. What is the purpose of subnetting in network configuration?": ["a) Dividing a large network into smaller networks", "b) Encrypting network traffic", "c) Assigning IP addresses", "d) Managing network security", {"Answer": "a"}],
    "17. Which protocol is used for secure remote access to a network?": ["a) VPN", "b) FTP", "c) HTTP", "d) SMTP", {"Answer": "a"}],
    "18. What is the purpose of DNS in network configuration?": ["a) Translating domain names to IP addresses", "b) Assigning IP addresses dynamically", "c) Filtering network traffic", "d) Managing network security", {"Answer": "a"}],
    "19. Which TCP/IP protocol is responsible for reliable data delivery?": ["a) TCP", "b) IP", "c) UDP", "d) ICMP", {"Answer": "a"}],
    "20. What is the purpose of a proxy server in network configuration?": ["a) Filtering and caching network traffic", "b) Assigning IP addresses", "c) Encrypting network communication", "d) Managing network security", {"Answer": "a"}],
    "2. Which protocol is used for email communication?": ["a) FTP", "b) SMTP", "c) HTTP", "d) DNS", {"Answer": "b"}],
    "4. Which command is used to display the IP configuration of a Windows machine?": ["a) ipconfig", "b) ifconfig", "c) netstat", "d) ping", {"Answer": "a"}],
    "5. What is the maximum length of a USB cable without using a hub?": ["a) 1 meter", "b) 2 meters", "c) 3 meters", "d) 5 meters", {"Answer": "d"}],
    "6. What is the binary equivalent of the decimal number 10?": ["a) 1100", "b) 1010", "c) 1001", "d) 0001", {"Answer": "b"}],
    "7. Which RAID level provides both redundancy and improved performance?": ["a) RAID 0", "b) RAID 1", "c) RAID 5", "d) RAID 10", {"Answer": "d"}],
    "8. What is the default port number for HTTPS?": ["a) 22", "b) 80", "c) 443", "d) 3389", {"Answer": "c"}],
    "9. Which command is used to change directory in a Unix-like operating system?": ["a) cd", "b) ls", "c) rm", "d) cp", {"Answer": "a"}],
    "10. What is the purpose of DHCP?": ["a) Assigning IP addresses", "b) Sending email", "c) Resolving domain names", "d) Encrypting data", {"Answer": "a"}],
    "11. Which programming language is used to develop Android apps?": ["a) Java", "b) C#", "c) Python", "d) Ruby", {"Answer": "a"}],
    "12. What is the file extension for a Python script?": ["a) .txt", "b) .exe", "c) .py", "d) .doc", {"Answer": "c"}],
    "13. Which SQL keyword is used to retrieve data from a database table?": ["a) SELECT", "b) INSERT", "c) UPDATE", "d) DELETE", {"Answer": "a"}],
    "15. What is the purpose of a firewall?": ["a) Blocking unauthorized access", "b) Increasing network speed", "c) Encrypting data", "d) Backing up files", {"Answer": "a"}],
    "16. What is the World Wide Web consortium responsible for?": ["a) Developing web standards", "b) Managing domain names", "c) Creating social media platforms", "d) Building computer hardware", {"Answer": "a"}],
    "18. What is the purpose of an if statement in programming?": ["a) Conditionally executing code", "b) Declaring variables", "c) Iterating over a collection", "d) Handling exceptions", {"Answer": "a"}],
    "19. What does the acronym VPN stand for?": ["a) Virtual Private Network", "b) Virus Protection Network", "c) Virtual Protocol Network", "d) Verified Private Network", {"Answer": "a"}],
    "20. Which data structure uses First-In, First-Out (FIFO) ordering?": ["a) Stack", "b) Queue", "c) Linked List", "d) Tree", {"Answer": "b"}],
    "39. Which of the following is a Microsoft cloud-based service for database hosting and management?": ["a) Azure Active Directory (Azure AD)", "b) Microsoft Intune", "c) Microsoft Azure Rights Management (Azure RMS)", "d) Azure SQL Database", {"Answer": "d"}],
    "40. Which Windows Server role is used for remote desktop session hosting and virtual desktop infrastructure?": ["a) Remote Desktop Services (RDS)", "b) Active Directory Lightweight Directory Services (AD LDS)", "c) Internet Information Services (IIS)", "d) Windows Server Update Services (WSUS)", {"Answer": "a"}],
    "41. Which PowerShell cmdlet is used to create a new DNS record in Windows Server?": ["a) New-DnsServerResourceRecord", "b) Set-DnsServerResourceRecord", "c) Add-DnsServerResourceRecord", "d) Create-DnsServerResourceRecord", {"Answer": "a"}],
    "42. Which RAID level provides fault tolerance by striping data across multiple disks with distributed double parity information?": ["a) RAID 0", "b) RAID 1", "c) RAID 5", "d) RAID 6", {"Answer": "d"}],
    "44. Which of the following is a Microsoft cloud-based service for file storage and sharing?": ["a) Azure Active Directory (Azure AD)", "b) Microsoft Intune", "c) Microsoft Azure Rights Management (Azure RMS)", "d) Azure Files", {"Answer": "d"}],
    "45. Which Windows Server role is used for print server management and print queue control?": ["a) Print Management", "b) Remote Desktop Services (RDS)", "c) Internet Information Services (IIS)", "d) Windows Server Update Services (WSUS)", {"Answer": "a"}],
    "47. Which RAID level provides fault tolerance by striping data across multiple disks with parity information and a hot spare?": ["a) RAID 0", "b) RAID 1", "c) RAID 5", "d) RAID 6", {"Answer": "c"}],
    "48. Which Windows Server feature is used for centralized certificate enrollment and management?": ["a) Active Directory Certificate Services (AD CS)", "b) Remote Desktop Services (RDS)", "c) Network Policy and Access Services (NPAS)", "d) Windows Server Update Services (WSUS)", {"Answer": "a"}],
    "49. Which of the following is a Microsoft cloud-based service for virtual network management?": ["a) Azure Active Directory (Azure AD)", "b) Microsoft Intune", "c) Microsoft Azure Rights Management (Azure RMS)", "d) Azure Virtual Network", {"Answer": "d"}],
    "51. Which PowerShell cmdlet is used to create a new DHCP reservation in Windows Server?": ["a) Add-DhcpServerv4Reservation", "b) Set-DhcpServerv4Reservation", "c) New-DhcpServerv4Reservation", "d) Create-DhcpServerv4Reservation", {"Answer": "c"}],
    "52. Which RAID level provides fault tolerance by striping data across multiple disks with mirrored sets and a hot spare?": ["a) RAID 0", "b) RAID 1", "c) RAID 5", "d) RAID 10", {"Answer": "d"}],
    "56. Which PowerShell cmdlet is used to create a new virtual network adapter in Hyper-V?": ["a) New-VMNetworkAdapter", "b) Set-VMNetworkAdapter", "c) Add-VMNetworkAdapter", "d) Create-VMNetworkAdapter", {"Answer": "a"}],
    "62. Which RAID level provides fault tolerance by striping data across multiple disks with dual parity information?": ["a) RAID 0", "b) RAID 1", "c) RAID 5", "d) RAID 6", {"Answer": "d"}],
    "68. Which Windows Server feature is used for centralized monitoring and performance analysis?": ["a) Event Viewer", "b) Performance Monitor", "c) Windows Firewall with Advanced Security", "d) Windows Admin Center", {"Answer": "b"}],
}
